server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment-service
          uri: http://localhost:8082
          predicates:
            - Path=/payment-service/**
          filters:
            - StripPrefix=1
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth-service/**
          filters:
            - StripPrefix=1
        - id: card-service
          uri: http://localhost:8082
          predicates:
            - Path=/card-service/**
          filters:
            - StripPrefix=1
        - id: fraud-service
          uri: http://localhost:8083
          predicates:
            - Path=/fraud-service/**
          filters:
            - StripPrefix=1
        - id: notification-service
          uri: http://localhost:8086
          predicates:
            - Path=/notification-service/**
          filters:
            - StripPrefix=1
        - id: audit-service
          uri: http://localhost:8087
          predicates:
            - Path=/audit-service/**
          filters:
            - StripPrefix=1
        - id: loan-service
          uri: http://localhost:8083
          predicates:
            - Path=/loan-service/**
          filters:
            - StripPrefix=1

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info
